# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1080u03__-C1miwo6xisX6uduQOrJ9wXO
"""

def primenumber(n):
  if n == 0:
    print("Not a Prime Number")
  elif n == 1:
    print("Prime Number")
  elif n > 1:
    for i in range(2, n):
      if n%i == 0:
        print("Not a Prime number")
        break
      else:
        print("Prime number")
        break
  else:
    ("Not a Prime number")