# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YjNCT8VeP62URxo_xMheQZQMp-Oh549A
"""

altitude = int(input("Enter the altitude: "))
if altitude <= 1000:
  print("Safe to land")
elif altitude > 1000 and altitude < 5000:
  print("Bring down to 1000ft.")
else:
  print("Turn around and try later.")