# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zbyNyXypYKpyfJCtVaUbOZMf4vubJXTT
"""

a = float(input("Enter first number"))
b = float(input("Enter second number"))
s = a - b 
m = a * b
d = a / b
print("The subtracted value is", s)
print("The multiplied value is", m)
print("The divided value is", d)

