# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-iq-k6gA2E2TaF1Km5SQzj3ngo3MSjNl
"""

participants = []
max = int(input("Enter the number of participants: "))
for i in range(max):
  x = input("Enter the name: ")
  participants.append(x)

import random
n = random.randint(0, max-1)
participants[n]

